name: Terraform Deployment
on:
  push:
    branches:
      - main
    paths:
      - "**.tf"
      - "code/infra/**"
      - ".github/workflows/terraform.yml"

  pull_request:
    branches:
      - main
    paths:
      - "**.tf"
      - "code/infra/**"
      - ".github/workflows/terraform.yml"

jobs:
  terraform:
    uses: ./.github/workflows/_terraformEnvironmentTemplate.yml
    name: "Terraform Deployment"
    with:
      environment: "dev"
      config: "PerfectThymeTech"
      terraform_version: "1.9.6"
      node_version: 20
      working_directory: "./code/infra"
      tenant_id: "37963dd4-f4e6-40f8-a7d6-24b97919e452"
      subscription_id: "e82c5267-9dc4-4f45-ac13-abdd5e130d27"
      log_level_test: "TRACE"
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
